global:
  scrape_interval:     15s
alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  - job_name: 'prometheusJob'
    static_configs:
      - targets: ['192.168.33.10:9090']
  - job_name: 'jenkinsJob'
    metrics_path: /prometheus
    static_configs:
      - targets: ['192.168.33.10:8080']
